config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to:"items#index"
  get 'purchase/index'
  get 'purchase/done'

  resources :users, only: [:show]

  resources :items do
  # resources :items, only: [:index, :new, :create, :show, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    get :purchase, on: :member
    get 'pay', to: 'purchase#pay'
    resources :purchase, only: [:show] do
      collection do
        post 'done', to: 'purchase#done'
      end
    end
  end

  resources :cards, only: [:new, :show] do
    collection do
      get 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      delete 'delete', to: 'cards#delete'
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  validates :postalcode, :prefecture, :city_town, :house_number, presence: true
  enum prefecture:{
    北海道:0,青森県:1,岩手県:2,宮城県:3,秋田県:4,山形県:5,福島県:6,
    茨城県:7,栃木県:8,群馬県:9,埼玉県:10,千葉県:11,東京都:12,神奈川県:13,
    新潟県:14,富山県:15,石川県:16,福井県:17,山梨県:18,長野県:19,
    岐阜県:20,静岡県:21,愛知県:22,三重県:23,
    滋賀県:24,京都府:25,大阪府:26,兵庫県:27,奈良県:28,和歌山県:29,
    鳥取県:30,島根県:31,岡山県:32,広島県:33,山口県:34,
    徳島県:35,香川県:36,愛媛県:37,高知県:38,
    福岡県:39,佐賀県:40,長崎県:41,熊本県:42,大分県:43,宮崎県:44,鹿児島県:45, 
    沖縄県:46
  }
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :items
  has_ancestry

end

app/models/feehash.rb
class Feehash < ActiveHash::Base
  self.data = [
      {id: 1, name: '送料込み（出品者負担）'},{id: 2, name: '着払い（購入者負担）'}
  ]
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :url, ImageUploader
  belongs_to :item
  
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :saler, class_name: "User", optional: true
  belongs_to :buyer, class_name: "User", optional: true
  has_many :images, dependent: :destroy
  validates :images, :name, :text, :status, :fee, :prefecture_id, :shipping, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 50 }

  accepts_nested_attributes_for :images, allow_destroy: true
  

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :statushash
  belongs_to_active_hash :feehash
  belongs_to_active_hash :shippinghash

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/shippinghash.rb
class Shippinghash < ActiveHash::Base
  self.data = [
      {id: 1, name: '1~2日で発送'},{id: 2, name: '2~3日で発送'},{id: 3, name: '4~7日で発送'}
  ]
end

app/models/statushash.rb
class Statushash < ActiveHash::Base
  self.data = [
      {id: 1, name: '新品、未使用'},{id: 2, name: '未使用に近い'},
      {id: 3, name: '目立った傷や汚れなし'},{id: 4, name: 'やや傷や汚れあり'},
      {id: 5, name: '傷や汚れあり'},{id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/statusselect.rb
class Statusselect < ActiveHash::Base
  self.data = [
      {id: 1, name: '新品、未使用'},{id: 2, name: '未使用に近い'},
      {id: 3, name: '目立った傷や汚れなし'},{id: 4, name: 'やや傷や汚れあり'},
      {id: 5, name: '傷や汚れあり'},{id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, :email, :password, :first_name, :last_name, :birthday, :first_name_kana, :last_name_kana,
            :send_first_name, :send_last_name, :send_first_name_kana, :send_last_name_kana, presence: true
  validates :nickname, uniqueness: true
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  validates :password, length: { minimum: 7 }
  has_many :items
  has_many :cards
  has_one :address
  accepts_nested_attributes_for :address

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :purchase]
  def index
    @items = Item.order("created_at desc").limit(6)

  end

  def new
    @item = Item.new
    @item.images.new
    #セレクトボックスの初期値設定
    @category_parent_array = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end

  def purchase
    @cards = Card.where(user_id: current_user.id)
    unless @cards.present?
      redirect_to new_card_path, method: :get
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path, notice: '投稿が送信されました'
    else
      @category_parent_array = ["---"]
      #データベースから、親カテゴリーのみ抽出し、配列化
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
      end
      redirect_to new_item_path, notice: '必須項目を入力してください。'
    end
  end

  def show
    @item_status = Statushash.find(@item.status)
    @item_fee = Feehash.find(@item.fee)
    @item_shipping = Shippinghash.find(@item.shipping)
  end

  def edit
    grandchild_category = @item.category
    child_category = grandchild_category.parent


    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
    
  end

  def update
    if @item.update(item_params)
      redirect_to item_path, notice: '投稿が更新されました'
    else
      @category_parent_array = ["---"]
      #データベースから、親カテゴリーのみ抽出し、配列化
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
      end
      flash.now[:alert] = '必須項目を入力してください。'
      render :edit
    end
  end

  def destroy
    if @item.destroy
      render :destroy
    else
      flash.now[:alert] = '商品出品取り消しに失敗しました。'
      render :show
    end
  end

  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end


  private
  def item_params
    params.require(:item).permit( :name, :text, :brand, :status, :category_id, :fee, :prefecture_id, :shipping, :price, images_attributes: [:_destroy,:id,:url]).merge( saler_id: current_user.id)
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_footer.html.haml
.footer
  .footer-top
    .footer-top__inner
      .footer-top__inner__title
        だれでもかんたん、人生を変えるフリマアプリ。
      .footer-top__inner__text
        今すぐ、無料ダウンロード!!
      .footer-top__inner__icon
        .footer-top__inner__icon__app-btn
        .footer-top__inner__icon__google-btn
  .footer-bottom
    %ul.footer-bottom__contents
      %li.footer-bottom__contents__content__left
        .footer-bottom__contents__content__left__head
          FURIMAについて
        %ul.footer-bottom__content__left__body
          %li.footer-bottom__content__left__body-a
            = link_to "会社概要欄"
          %li.footer-bottom__content__left__body-b
            = link_to "プライバシーポリシー"
          %li.footer-bottom__content__left__body-c
            = link_to "FURIMA利用規約"
          %li.footer-bottom__content__left__body-d
            = link_to "ポイントに関する特約"
      %li.footer-bottom__contents__content__center
        .footer-bottom__contents__content__center__head
          FURIMAを見る
        %ul.footer-bottom__content__center__body
          %li.footer-bottom__content__center__body-a
          = link_to "カテゴリー一覧"
          %li.footer-bottom__content__center__body-b
          = link_to "ブランド一覧"
      %li.footer-bottom__contents__content__rigth
        .footer-bottom__contents__content__rigth__head
          ヘルプ&ガイド
        %ul.footer-bottom__content__rigth__body
          %li.footer-bottom__content__rigth__body-a
          = link_to "FRIMAガイド"
          %li.footer-bottom__content__rigth__body-b
          = link_to "FURIMAロゴ利用ガイドライン"
          %li.footer-bottom__content__rigth__body-c
          = link_to "お知らせ"
      .footer-bottom__image
        .footer-bottom__image__sub
        .footer-bottom__image__title
        　　© FURIMA

app/views/items/_header.html.haml
.header
  .header__inner
    .header__inner__main-header
      .header__inner__main-header__furima-image
        = link_to root_path do
          = image_tag "logo.png", class: "header-image"
      .header__inner__main-header__search-box
        .header__inner__main-header__search-box__search-input
          = form_with(url: "#", local: true, method: :get, class: "search-form") do |form|
            = form.text_field :date, placeholder: "キーワードから探す", class: "search-text"
            .header__inner__main-header__seach-box__search-input__search
              = form.submit :　, class: "search-btn"


    .header__inner__nav
      .header__inner__nav__list-left
        .header__inner__nav__list-left__category
          = link_to "#", class: "btn-category" do
            カテゴリー
        .header__inner__nav__list-left__brand
          = link_to "#", class: "btn-brand" do
            ブランド
      .header__inner__nav__list-right
        .header__inner__nav__list-right__box-left
          - if user_signed_in?
            = link_to user_path(current_user), class: "left-btn" do
              マイページ 
          - else
            = link_to new_user_session_path, class: "left-btn" do
              ログイン
        .header__inner__nav__list-right__box-right
          - if user_signed_in?
            = link_to destroy_user_session_path, method: :delete, class: "right-btn" do
              ログアウト
          - else
            = link_to new_user_registration_path, class: "right-btn" do
              新規会員登録

app/views/items/_main.bottom.html.haml
.main
  .main__bottom
    .main__bottom__top
      .p ピックアップカテゴリー
      .main__bottom__top__name
        新規投稿商品
      .main__bottom__top__content-box
        - @items.each do |item|
          - if item.buyer_id.present?
          - else "no buyer_id"
            .main__bottom__top__content-box__menu
              = link_to  item_path(item.id),class: "item-menu" do
                .main__bottom__top__content-box__menu__img
                  = image_tag item.images[0].url.url
                .main__bottom__top__content-box__menu__text__top
                  = item.name
                .main__bottom__top__content-box__menu__text__middle
                  = item.price
                  .main__bottom__top__content-box__menu__text__middle__star
                    ★０
                .main__bottom__top__content-box__menu__text__bottom
                  (税込)

app/views/items/_main.top.html.haml
.maintop
  .maintop__mainfirst
    .maintop__mainfirst__content
      .maintop__mainfirst__content__Advertisement
        人生を変えるフリマアプリ
      .maintop__mainfirst__content__Description
        .p FURIMAは誰でもかんたんに出品・購入できる
        .br フリマアプリです
      .maintop__mainfirst__content__btn
        .maintop__mainfirst__content__btn__abtn
          = link_to "　", class: "contents__btn" 

        .maintop__mainfirst__content__btn__bbtn
          = link_to "　", class: "contents__btn" 


  .maintop__heading
    .maintop__heading__titl
      FURIMAが選ばれる３つの理由
    .maintop__heading__reasons
      .maintop__heading__reasons__reason
        .maintop__heading__reasons__reason__pict-left
          .maintop__heading__reasons__reason__pict-left__number-left
            1
          .maintop__heading__reasons__reason__pict-left__img-left
        .maintop__heading__reasons__reason__text
          .maintop__heading__reasons__reason__text__Continued
            ３分 
          .maintop__heading__reasons__reason__text__further
            ですぐに出品
        .maintop__heading__reasons__reason__Supplement
          スマホで入力するだけで簡単に出品できる！
      .maintop__heading__reasons__reason
        .maintop__heading__reasons__reason__pict-center
          .maintop__heading__reasons__reason__pict-center__number-center
            2
          .maintop__heading__reasons__reason__pict-center__img-center
        .maintop__heading__reasons__reason__text
          .maintop__heading__reasons__reason__text__Continued
            シンプル
          .maintop__heading__reasons__reason__text__further
            で使いやすい
        .maintop__heading__reasons__reason__Supplement
          めんどくさい入力は必要なく、検索も購入もスムーズ
      .maintop__heading__reasons__reason
        .maintop__heading__reasons__reason__pict-right
          .maintop__heading__reasons__reason__pict-right__number-right
            3
          .maintop__heading__reasons__reason__pict-right__img-right
        .maintop__heading__reasons__reason__text
          .maintop__heading__reasons__reason__text__further
            手数料 
          .maintop__heading__reasons__reason__text__Continued
            業界最安
        .maintop__heading__reasons__reason__Supplement
          最大で3%でお得に出品&購入

  .maintop__heading-second
    .maintop__heading-second__titl
      FURIMAの特徴
    .maintop__heading-second__reasons
      .maintop__heading-second__reasons__reason
        .maintop__heading-second__reasons__reason__pict-left
          .maintop__heading-second__reasons__reason__pict-left__img-left
        .maintop__heading-second__reasons__reason__text
          簡単に売り買いできる
        .maintop__heading-second__reasons__reason__Supplement
          スマホ１つで、いつでもどこでも簡単に出品・購入が可能！
      .maintop__heading-second__reasons__reason
        .maintop__heading-second__reasons__reason__pict-center
          .maintop__heading-second__reasons__reason__pict-center__img-center
        .maintop__heading-second__reasons__reason__text
          売上金は即時振り込みに対応
        .maintop__heading-second__reasons__reason__Supplement
          午前９時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
      .maintop__heading-second__reasons__reason
        .maintop__heading-second__reasons__reason__pict-right
          .maintop__heading-second__reasons__reason__pict-right__img-right
        .maintop__heading-second__reasons__reason__text
          様々な支払いに対応
        .maintop__heading-second__reasons__reason__Supplement
          お支払いはクレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  .maintop__mainsecond
    .maintop__mainsecond__content
      .maintop__mainsecond__content__Advertisement
        会員数日本一位
      .maintop__mainsecond__content__Description
        .p FURIMAは、フリマアプリで最も人気。
        .br 出品・購入回数も業界最多です！
        .br ほしかったあの商品に出会えるかもしれません。
      .maintop__mainsecond__content__btn
        .maintop__mainsecond__content__btn__cbtn
          = link_to "　", class: "contents__btn"
        .maintop__mainsecond__content__btn__dbtn
          = link_to "　", class: "contents__btn"

app/views/items/destroy.html.haml
= render "header"
.delete-result
  .delete-result__main
    .delete-result__main__text
      削除しました
    .delete-result__main__return
      = link_to 'トップページに戻る', root_path, class:"return-btn"
= render "footer"

app/views/items/index.html.haml
.wrapper
  = render "header"
  = render "main.top"
  = render "main.bottom"
  = render "footer"
- if user_signed_in?
  = link_to  new_item_path do
    .exhibition
      .exhibition__exhibition-text
        出品する
      .exhibition__exhibition-icon

app/views/items/purchase.html.haml
.product-purchase
  .product-purchase__box
    .product-purchase__box__heder
      .product-purchase__box__heder__frame
        .product-purchase__box__heder__frame__link
          .product-purchase__box__heder__frame__link__image
            = link_to root_path do
              = image_tag "logo.png", class: "product-purchase__box__heder__frame__link__image"
    .product-purchase__box__main
      .product-purchase__box__main__frame
        .product-purchase__box__main__frame__top
          購入内容の確認
      .product-purchase__box__main__second
        .product-purchase__box__main__second__inner
          .product-purchase__box__main__second__inner__item
            .product-purchase__box__main__second__inner__item__image
              = image_tag ("#{@item.images[0].url}"), size: "100x100", class: "product_imge"
            .product-purchase__box__main__second__inner__item__detail
              .product-purchase__box__main__second__inner__item__detail__name
                = @item.name
              .product-purchase__box__main__second__inner__item__detail__bold
                .product-purchase__box__main__second__inner__item__detail__bold__price
                  = @item.price
                .product-purchase__box__main__second__inner__item__detail__bold__tax-included
                  （税込み）送料込み
      .product-purchase__box__main__third
        .product-purchase__box__main__third__inner
          .product-purchase__box__main__third__inner__frame
            .product-purchase__box__main__third__inner__frame__price-table
              .product-purchase__box__main__third__inner__frame__price-table__bold
                .product-purchase__box__main__third__inner__frame__price-table__bold__prace-cell
                  支払金額
                .product-purchase__box__main__third__inner__frame__price-table__bold__prace
                  .product-purchase__box__main__third__inner__frame__price-table__bold__prace__pay
                    = @item.price
            .product-purchase__box__main__third__inner__frame__point
              .product-purchase__box__main__third__inner__frame__point__accordion-parent
                .product-purchase__box__main__third__inner__frame__point__accordion-parent__check
                  .product-purchase__box__main__third__inner__frame__point__accordion-parent__in
                  .product-purchase__box__main__third__inner__frame__point__accordion-parent__icon
                  .product-purchase__box__main__third__inner__frame__point__accordion-parent__point
      
      .product-purchase__box__main__fifth
        .product-purchase__box__main__fifth__inner
          .product-purchase__box__main__fifth__inner__shipping-address
            配送先
          .product-purchase__box__main__fifth__inner__text
            .product-purchase__box__main__fifth__inner__text__icon
              .product-purchase__box__main__fifth__inner__text__icon__text
          .product-purchase__box__main__fifth__inner__sixth
            .product-purchase__box__main__fifth__inner__sixth__text
            .product-purchase__box__main__fifth__inner__sixth__bold
              - if !Card.nil?
                = link_to '購入する',item_pay_path(@item), method: :get ,class:"buy-btn"
              - else
                = link_to 'カード情報を登録してください', new_card_path, method: :get ,class:"buy-btn"
            .product-purchase__box__main__fifth__inner__sixth__app
            .product-purchase__box__main__fifth__inner__sixth__logos
  .product-purchase__footer
    .product-purchase__footer__sub
      .product-purchase__footer__sub__box
        .product-purchase__footer__sub__box__text
          .product-purchase__footer__sub__box__text__link
            プライバシーポリシー
        .product-purchase__footer__sub__box__text
          .product-purchase__footer__sub__box__text__link
            フリマ利用規約
        .product-purchase__footer__sub__box__text
          .product-purchase__footer__sub__box__text__link
            特定商取引に関する表記
    .product-purchase__footer__image
      .product-purchase__footer__image__pasting
    .product-purchase__footer__logo
      .product-purchase__footer__logo__pasting
        © Furima

app/views/items/show.html.haml
= render "header"
.details-main
  .details-main__top


  .details-main__bottom
    .details-main__bottom__product 
      .details-main__bottom__product__title 
        = @item.name
      .details-main__bottom__product__edit-dest
        .details-main__bottom__product__edit-dest__box
          - if user_signed_in? && current_user.id == @item.saler_id
            = link_to '編集', "#", class: "details-main__bottom__product__edit-dest__box__edit" 
          - else
        .details-main__bottom__product__edit-dest__box
          - if user_signed_in? && current_user.id == @item.saler_id
            = link_to '削除', item_path(@item.id), method: :delete,class: "details-main__bottom__product__edit-dest__box__dest" 
          - else
      .details-main__bottom__product__img
        = image_tag ("#{@item.images[0].url}"), size: "100%x100%", class: "large-img"
      .details-main__bottom__product__img-bottom
        .details-main__bottom__product__img-bottom__picts
          = image_tag ("#{@item.images[0].url}"), size: "100%x100%", class: "small-img"
        .details-main__bottom__product__img-bottom__picts
          = image_tag ("#{@item.images[0].url}"), size: "100%x100%", class: "small-img"
        .details-main__bottom__product__img-bottom__picts
          -# = image_tag @item.images[1].url.url, size: "100x100", class: "small-img" // 表示数を変える可能性があるため
      .details-main__bottom__product__img-price  
        = @item.price
      .details-main__bottom__product__img-text
        (税込)送料込み
      .details-main__bottom__product__img-text-bottom
        = @item.text
      .details-main__bottom__product__img-table
        .details-main__bottom__product__img-table__left
          出品者
        .details-main__bottom__product__img-table__right
          = @item.saler.nickname
      .details-main__bottom__product__img-table
        .details-main__bottom__product__img-table__left
          カテゴリー
        .details-main__bottom__product__img-table__right
          = @item.category.name
      .details-main__bottom__product__img-table
        .details-main__bottom__product__img-table__left
          ブランド
        .details-main__bottom__product__img-table__right
          = @item.brand
      .details-main__bottom__product__img-table
        .details-main__bottom__product__img-table__left
          商品の状態
        .details-main__bottom__product__img-table__right
          = @item_status.name
      .details-main__bottom__product__img-table
        .details-main__bottom__product__img-table__left
          配送料の負担
        .details-main__bottom__product__img-table__right
          = @item_fee.name
      .details-main__bottom__product__img-table
        .details-main__bottom__product__img-table__left
          発送元の地域
        .details-main__bottom__product__img-table__right
          = @item.prefecture.name
      .details-main__bottom__product__img-table
        .details-main__bottom__product__img-table__left
          発送日の目安
        .details-main__bottom__product__img-table__right
          = @item_shipping.name
      .details-main__bottom__product__img-boxes
        .details-main__bottom__product__img-boxes__left
          ★　お気に入り　０
        .details-main__bottom__product__img-boxes__right
          🏴　不適切な商品を通報

    .details-main__bottom__space
    .details-main__bottom__comment
      .details-main__bottom__comment__form
      .details-main__bottom__comment__attention
        .details-main__bottom__comment__attention__top-text
          相手のことを考え丁寧なコメントを心がけましょう。
        .details-main__bottom__comment__attention__bottom-text
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .details-main__bottom__comment__btn
        .details-main__bottom__comment__btn__box
          .details-main__bottom__comment__btn__box__send
            💬コメントする
          .details-main__bottom__comment__btn__box__buy
            - if user_signed_in? && current_user.id == @item.saler_id
            - elsif user_signed_in?
              = link_to '購入する', purchase_item_path, method: :get,class:"switch-btn"
            - else
              = link_to '登録する', new_user_registration_path, class:"switch-btn"
    .details-main__bottom__third-content
      .details-main__bottom__third-content__left
        ＜前の商品
      .details-main__bottom__third-content__right
        次の商品＞
    .details-main__bottom__forth-content
      aaa
    
    = render "footer"