config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to:"items#index"
  get 'purchase/index'
  get 'purchase/done'

  resources :users, only: [:show]

  resources :items do
  # resources :items, only: [:index, :new, :create, :show, :update, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    get :purchase, on: :member
    get 'pay', to: 'purchase#pay'
    resources :purchase, only: [:show] do
      collection do
        post 'done', to: 'purchase#done'
      end
    end
  end

  resources :cards, only: [:new, :show] do
    collection do
      get 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      delete 'delete', to: 'cards#delete'
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  validates :postalcode, :prefecture, :city_town, :house_number, presence: true
  enum prefecture:{
    北海道:0,青森県:1,岩手県:2,宮城県:3,秋田県:4,山形県:5,福島県:6,
    茨城県:7,栃木県:8,群馬県:9,埼玉県:10,千葉県:11,東京都:12,神奈川県:13,
    新潟県:14,富山県:15,石川県:16,福井県:17,山梨県:18,長野県:19,
    岐阜県:20,静岡県:21,愛知県:22,三重県:23,
    滋賀県:24,京都府:25,大阪府:26,兵庫県:27,奈良県:28,和歌山県:29,
    鳥取県:30,島根県:31,岡山県:32,広島県:33,山口県:34,
    徳島県:35,香川県:36,愛媛県:37,高知県:38,
    福岡県:39,佐賀県:40,長崎県:41,熊本県:42,大分県:43,宮崎県:44,鹿児島県:45, 
    沖縄県:46
  }
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :items
  has_ancestry

end

app/models/feehash.rb
class Feehash < ActiveHash::Base
  self.data = [
      {id: 1, name: '送料込み（出品者負担）'},{id: 2, name: '着払い（購入者負担）'}
  ]
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :url, ImageUploader
  belongs_to :item
  
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :saler, class_name: "User", optional: true
  belongs_to :buyer, class_name: "User", optional: true
  has_many :images, dependent: :destroy
  validates :images, :name, :text, :status, :fee, :prefecture_id, :shipping, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 50 }

  accepts_nested_attributes_for :images, allow_destroy: true
  

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :statushash
  belongs_to_active_hash :feehash
  belongs_to_active_hash :shippinghash

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/shippinghash.rb
class Shippinghash < ActiveHash::Base
  self.data = [
      {id: 1, name: '1~2日で発送'},{id: 2, name: '2~3日で発送'},{id: 3, name: '4~7日で発送'}
  ]
end

app/models/statushash.rb
class Statushash < ActiveHash::Base
  self.data = [
      {id: 1, name: '新品、未使用'},{id: 2, name: '未使用に近い'},
      {id: 3, name: '目立った傷や汚れなし'},{id: 4, name: 'やや傷や汚れあり'},
      {id: 5, name: '傷や汚れあり'},{id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/statusselect.rb
class Statusselect < ActiveHash::Base
  self.data = [
      {id: 1, name: '新品、未使用'},{id: 2, name: '未使用に近い'},
      {id: 3, name: '目立った傷や汚れなし'},{id: 4, name: 'やや傷や汚れあり'},
      {id: 5, name: '傷や汚れあり'},{id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, :email, :password, :first_name, :last_name, :birthday, :first_name_kana, :last_name_kana,
            :send_first_name, :send_last_name, :send_first_name_kana, :send_last_name_kana, presence: true
  validates :nickname, uniqueness: true
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  validates :password, length: { minimum: 7 }
  has_many :items
  has_many :cards
  has_one :address
  accepts_nested_attributes_for :address

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"

  def new
    cards = Card.where(user_id: current_user.id)
    redirect_to action: "show" if cards.exists?
  end

  def pay 
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete 
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to root_path
  end

  def show 
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to root_path
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/new.html.haml
.pay-header
  .pay-header__box
    .pay-header__box__heder
      .pay-header__box__heder__frame
        .pay-header__box__heder__frame__link
          .pay-header__box__heder__frame__link__image

  .pay-header__box__middle
    .pay-header__box__middle__frame
      .pay-header__box__middle__frame__top
        = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %label カード番号
          = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          %br
          %label 有効期限
          %select#exp_month{name: "exp_month", type: "text"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %span 月/
          %select#exp_year{name: "exp_year", type: "text"}
            %option{value: ""} --
            %option{value: "2019"}19
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          %span 年
          %br
          %label セキュリティコード
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
          #card_token
          = submit_tag "追加する", id: "token_submit"
  
  .pay-header__footer
    .pay-header__footer__sub
      .pay-header__footer__sub__box
        .pay-header__footer__sub__box__text
          .pay-header__footer__sub__box__text__link
            プライバシーポリシー
        .pay-header__footer__sub__box__text
          .pay-header__footer__sub__box__text__link
            フリマ利用規約
        .pay-header__footer__sub__box__text
          .pay-header__footer__sub__box__text__link
            特定商取引に関する表記
    .pay-header__footer__image
      .pay-header__footer__image__pasting
    .pay-header__footer__logo
      .pay-header__footer__logo__pasting
        © Furima

app/views/cards/show.html.haml
.pay-header
  .pay-header__box
    .pay-header__box__heder
      .pay-header__box__heder__frame
        .pay-header__box__heder__frame__link
          .pay-header__box__heder__frame__link__image
            = link_to root_path do
              = image_tag "logo.png", class: "pay-header__box__heder__frame__link__image"

  .pay-header__box__middle
    .pay-header__box__middle__frame
      .pay-header__box__middle__frame__top
        %label 登録クレジットカード情報
        %br
        = "**** **** **** " + @default_card_information.last4
        %br
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
        = form_tag(delete_cards_path, method: :delete, id: 'charge-form',  name: "inputForm") do
          %input{ type: "hidden", name: "card_id", value: "" }
          %button 削除する

  .pay-header__footer
    .pay-header__footer__sub
      .pay-header__footer__sub__box
        .pay-header__footer__sub__box__text
          .pay-header__footer__sub__box__text__link
            プライバシーポリシー
        .pay-header__footer__sub__box__text
          .pay-header__footer__sub__box__text__link
            フリマ利用規約
        .pay-header__footer__sub__box__text
          .pay-header__footer__sub__box__text__link
            特定商取引に関する表記
    .pay-header__footer__image
      .pay-header__footer__image__pasting
    .pay-header__footer__logo
      .pay-header__footer__logo__pasting
        © Furima